import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState("en");
  const toggle = () => setLang(l => l === "en" ? "hi" : "en");
  const t = (key) => (TRANSLATIONS[lang][key] || TRANSLATIONS["en"][key] || key);
  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const LangToggle = () => {
  const { lang, toggle } = useLanguage();
  return (
    <button
      onClick={toggle}
      style={{
        background: "rgba(208,91,55,0.12)",
        border: "1px solid rgba(208,91,55,0.3)",
        color: "#E87A57",
        padding: "6px 14px",
        borderRadius: 100,
        fontSize: 13,
        fontWeight: 700,
        cursor: "pointer",
        fontFamily: "'DM Sans',sans-serif",
        transition: "background 0.2s",
      }}
      onMouseEnter={e => e.currentTarget.style.background = "rgba(208,91,55,0.22)"}
      onMouseLeave={e => e.currentTarget.style.background = "rgba(208,91,55,0.12)"}
    >
      {lang === "en" ? "हिंदी" : "English"}
    </button>
  );
};

const TRANSLATIONS = {
  en: {
    // NAV
    navHome: "Home",
    navServices: "Services",
    navPortfolio: "Portfolio",
    navPricing: "Pricing",
    navOrder: "Order",
    navContact: "Contact",
    navOrderBtn: "Order Now",

    // HOMEPAGE
    heroTag: "Fast Poster Design",
    heroHeading: "Professional Posters for Your Business,",
    heroHeading2: "Delivered Fast.",
    heroSub: "Marketing creatives for salons, gyms, cafes, kirana stores — delivered via WhatsApp in minutes.",
    heroCta: "Order on WhatsApp",
    heroPricing: "View Pricing",
    heroStat1: "⚡ 10–30 min delivery",
    heroStat2: "★ 4.9 rating",
    heroStat3: "100+ posters done",
    galleryTag: "Our work",
    galleryTitle: "Poster Gallery",
    galleryBtn: "View all",
    pricingTag: "Pricing",
    pricingTitle: "Try PosterBabu",
    pricingTitleHL: "today",
    pricingSub: "No commitment. No contracts. Just great posters.",
    pricingAllPlans: "View all monthly plans →",
    howTag: "Simple process",
    howTitle: "How PosterBabu",
    howTitleHL: "works",
    howStep1Title: "WhatsApp us",
    howStep1Desc: "Send your business name, what you want on the poster, and any details.",
    howStep2Title: "We design",
    howStep2Desc: "Our designer gets to work immediately and creates your poster in minutes.",
    howStep3Title: "Receive & post",
    howStep3Desc: "Get the HD file on WhatsApp — ready to post on Instagram or print.",
    howCta: "Start on WhatsApp",
    ctaTitle: "Ready to promote your business?",
    ctaSub: "Get your first poster in under 30 minutes.",
    ctaBtn: "Order Now — Starting ₹49",

    // OFFER CARDS
    offer1Tagline: "Quick template edit",
    offer1Name: "Fast Edit",
    offer1F1: "Edit existing poster",
    offer1F2: "Text or offer update",
    offer1F3: "Delivered fast",
    offer1Btn: "Edit My Poster",
    offer2Tagline: "Built for your business",
    offer2Name: "Custom Poster",
    offer2F1: "Custom poster design",
    offer2F2: "Instagram / WhatsApp size",
    offer2F3: "HD file delivery",
    offer2F4: "Delivered within an hour",
    offer2Btn: "Create My Poster",

    // SERVICES PAGE
    svcTag: "What we offer",
    svcTitle: "Everything your business needs to",
    svcTitleHL: "look great.",
    svcSub: "From street banners to viral social media posts — we handle every visual need of your local business, delivered fast via WhatsApp.",
    svcOrderBtn: "Order on WhatsApp",
    svcViewPricing: "View pricing",
    svcClickHint: "Click any card to order that service",
    svcCat1Title: "Shop Posters",
    svcCat1Desc: "Sale posters, opening announcements, discount offers, retail promotions.",
    svcCat2Title: "Social Media Designs",
    svcCat2Desc: "Instagram posts, Facebook creatives, festival greetings and promotions.",
    svcCat3Title: "Business Promotions",
    svcCat3Desc: "Posters for gyms, salons, cafes, tuition centers and local brands.",
    svcCat4Title: "Print Designs",
    svcCat4Desc: "High quality print-ready posters, flyers and banners.",
    svcStartingFrom: "Starting from",
    svcOrderThis: "Order this",
    svcHowTag: "Simple process",
    svcHowTitle: "How it",
    svcHowTitleHL: "works",
    svcStep1Title: "You WhatsApp us",
    svcStep1Desc: "Send your business name, what the poster is for, and any specific details or offers.",
    svcStep2Title: "We get to work",
    svcStep2Desc: "Our designer picks the right template and customises it fully to your business.",
    svcStep3Title: "Review & deliver",
    svcStep3Desc: "We send a draft. You approve or request changes. Final HD file delivered on WhatsApp.",
    svcWhoTag: "Our customers",
    svcWhoTitle: "Built for",
    svcWhoTitleHL: "local India",
    svcCtaTitle: "Ready to get your first poster?",
    svcCtaSub: "WhatsApp us now — delivered in under 30 minutes.",
    svcCtaBtn: "Order Now — ₹49",

    // PORTFOLIO PAGE
    portTag: "Our portfolio",
    portTitle: "Real posters for",
    portTitleHL: "real businesses",
    portSub: "Every poster below was made for an actual local business. Browse and pick a style — we'll customise it for yours.",
    portPriceNote: "🔥 All templates customised for just ₹49",
    portOrderBtn: "Order this poster",
    portClose: "Close",

    // PRICING PAGE
    priceTag: "Transparent pricing",
    priceTitle: "Simple &",
    priceTitleHL: "transparent pricing",
    priceSub: "No hidden fees. No contracts. Pay only for what you need.",
    priceOneTimeTitle: "One-time orders",
    priceOneTimeSub: "Perfect if you need a poster right now",
    priceMonthlyTitle: "Monthly plans",
    priceMonthlyBadge: "Best value",
    priceMonthlySub: "For businesses that post regularly",
    priceFaqTitle: "Frequently asked questions",
    priceCtaTitle: "Still not sure?",
    priceCtaSub: "Try a ₹49 Fast Edit first — no risk, no commitment.",
    priceCtaBtn: "Try for ₹49",
    pricePerMonth: "/month",
    pricePostersMonth: "posters / month",
    priceFestival: "Festival creatives",
    priceSupport: "WhatsApp support",
    pricePriority: "Priority support",
    priceCustom: "Custom campaign designs",
    priceMostPopular: "Most Popular",

    // ORDER PAGE
    orderTag: "Fast poster design",
    orderTitle: "Start your",
    orderTitleHL: "order",
    orderSub: "Most orders delivered in under 20 minutes. Draft first, pay after you're happy.",
    orderName: "Your name",
    orderNamePH: "e.g. Rahul Sharma",
    orderBusiness: "Business name",
    orderBusinessPH: "e.g. Sharma Kirana Store",
    orderType: "Service type",
    orderTypeSub: "For Fast Edit (₹49), pick a design from the Portfolio and we'll customise it for you",
    orderDetails: "Poster details — the more you tell us, the better the design 😎",
    orderDetailsPH: "What do you want on the poster? Include your offer, phone number, address, etc.",
    orderBtn: "Send to WhatsApp",
    orderT1: "No upfront payment",
    orderT2: "Draft first, pay later",
    orderT3: "HD file delivery",

    // CONTACT PAGE
    contactTag: "Get in touch",
    contactTitle: "We're here to",
    contactTitleHL: "help.",
    contactSub: "Have a question or want to place a custom order? Reach out — we respond fast.",
    contactDetailsTitle: "Contact details",
    contactDetailsSub: "Reach us on any of these channels",
    contactHoursTitle: "Business hours",
    contactWACta: "Chat on WhatsApp now",
    contactFormTitle: "Send a quick message",
    contactFormSub: "This will open WhatsApp with your message pre-filled.",
    contactYourName: "Your name",
    contactYourNamePH: "e.g. Rahul Sharma",
    contactEmailPhone: "Email or phone",
    contactEmailPhonePH: "How should we reach you?",
    contactMessage: "Message",
    contactMessagePH: "Write your question or request...",
    contactSendBtn: "Send via WhatsApp",
    contactSentTitle: "Message sent!",
    contactSentSub: "Your WhatsApp should have opened with your message pre-filled. We'll reply shortly!",
    contactSentBtn: "Send another message",
    contactUrgent: "Need something urgent outside hours? WhatsApp us — we try our best to respond.",

    // FOOTER
    footerTagline: "Fast, affordable poster design for local businesses across India. Starting at ₹49.",
    footerPages: "Pages",
    footerContact: "Contact",
    footerRights: "All rights reserved.",
    footerMade: "Made with ❤️ for local businesses in India",
  },

  hi: {
    // NAV
    navHome: "होम",
    navServices: "सर्विसेज़",
    navPortfolio: "पोर्टफोलियो",
    navPricing: "प्राइसिंग",
    navOrder: "ऑर्डर",
    navContact: "संपर्क",
    navOrderBtn: "अभी ऑर्डर करें",

    // HOMEPAGE
    heroTag: "फास्ट पोस्टर डिज़ाइन",
    heroHeading: "आपके बिज़नेस के लिए प्रोफेशनल पोस्टर,",
    heroHeading2: "झटपट डिलीवरी।",
    heroSub: "सैलून, जिम, कैफे, किराना स्टोर — WhatsApp पर मिनटों में पोस्टर पाएं।",
    heroCta: "WhatsApp पर ऑर्डर करें",
    heroPricing: "प्राइस देखें",
    heroStat1: "⚡ 10–30 मिनट में डिलीवरी",
    heroStat2: "★ 4.9 रेटिंग",
    heroStat3: "100+ पोस्टर बने",
    galleryTag: "हमारा काम",
    galleryTitle: "पोस्टर गैलरी",
    galleryBtn: "सभी देखें",
    pricingTag: "प्राइसिंग",
    pricingTitle: "PosterBabu आज़माएं",
    pricingTitleHL: "आज ही",
    pricingSub: "कोई कमिटमेंट नहीं। कोई कॉन्ट्रैक्ट नहीं। बस शानदार पोस्टर।",
    pricingAllPlans: "सभी मंथली प्लान देखें →",
    howTag: "आसान प्रोसेस",
    howTitle: "PosterBabu",
    howTitleHL: "कैसे काम करता है",
    howStep1Title: "WhatsApp करें",
    howStep1Desc: "अपना बिज़नेस नाम, पोस्टर में क्या चाहिए और डिटेल्स भेजें।",
    howStep2Title: "हम डिज़ाइन करते हैं",
    howStep2Desc: "हमारा डिज़ाइनर तुरंत काम शुरू करके मिनटों में पोस्टर बनाता है।",
    howStep3Title: "पाएं और पोस्ट करें",
    howStep3Desc: "WhatsApp पर HD फ़ाइल मिलेगी — Instagram पर पोस्ट या प्रिंट के लिए तैयार।",
    howCta: "WhatsApp पर शुरू करें",
    ctaTitle: "अपने बिज़नेस को प्रमोट करने के लिए तैयार हैं?",
    ctaSub: "30 मिनट से कम में पहला पोस्टर पाएं।",
    ctaBtn: "अभी ऑर्डर करें — सिर्फ ₹49 से",

    // OFFER CARDS
    offer1Tagline: "झटपट टेम्पलेट एडिट",
    offer1Name: "फास्ट एडिट",
    offer1F1: "मौजूदा पोस्टर एडिट",
    offer1F2: "टेक्स्ट या ऑफर अपडेट",
    offer1F3: "झटपट डिलीवरी",
    offer1Btn: "पोस्टर एडिट करें",
    offer2Tagline: "आपके बिज़नेस के लिए",
    offer2Name: "कस्टम पोस्टर",
    offer2F1: "कस्टम पोस्टर डिज़ाइन",
    offer2F2: "Instagram / WhatsApp साइज़",
    offer2F3: "HD फ़ाइल डिलीवरी",
    offer2F4: "एक घंटे के अंदर डिलीवरी",
    offer2Btn: "पोस्टर बनाएं",

    // SERVICES PAGE
    svcTag: "हम क्या करते हैं",
    svcTitle: "आपके बिज़नेस को शानदार दिखाने के लिए",
    svcTitleHL: "सब कुछ।",
    svcSub: "बैनर से लेकर वायरल सोशल मीडिया पोस्ट तक — आपके बिज़नेस की हर विज़ुअल ज़रूरत, WhatsApp पर झटपट।",
    svcOrderBtn: "WhatsApp पर ऑर्डर करें",
    svcViewPricing: "प्राइस देखें",
    svcClickHint: "सर्विस ऑर्डर करने के लिए कार्ड पर क्लिक करें",
    svcCat1Title: "दुकान के पोस्टर",
    svcCat1Desc: "सेल पोस्टर, ओपनिंग अनाउंसमेंट, डिस्काउंट ऑफर, रिटेल प्रमोशन।",
    svcCat2Title: "सोशल मीडिया डिज़ाइन",
    svcCat2Desc: "Instagram पोस्ट, Facebook क्रिएटिव, फेस्टिवल ग्रीटिंग और प्रमोशन।",
    svcCat3Title: "बिज़नेस प्रमोशन",
    svcCat3Desc: "जिम, सैलून, कैफे, ट्यूशन सेंटर और लोकल ब्रांड के लिए पोस्टर।",
    svcCat4Title: "प्रिंट डिज़ाइन",
    svcCat4Desc: "हाई क्वालिटी प्रिंट-रेडी पोस्टर, फ्लायर और बैनर।",
    svcStartingFrom: "शुरुआत",
    svcOrderThis: "यह ऑर्डर करें",
    svcHowTag: "आसान प्रोसेस",
    svcHowTitle: "कैसे",
    svcHowTitleHL: "काम करता है",
    svcStep1Title: "WhatsApp करें",
    svcStep1Desc: "अपना बिज़नेस नाम, पोस्टर किस चीज़ के लिए है और डिटेल्स भेजें।",
    svcStep2Title: "हम काम शुरू करते हैं",
    svcStep2Desc: "हमारा डिज़ाइनर सही टेम्पलेट चुनकर आपके बिज़नेस के हिसाब से कस्टमाइज़ करता है।",
    svcStep3Title: "रिव्यू और डिलीवरी",
    svcStep3Desc: "हम ड्राफ्ट भेजते हैं। आप अप्रूव करें या बदलाव बताएं। WhatsApp पर HD फ़ाइल मिलेगी।",
    svcWhoTag: "हमारे ग्राहक",
    svcWhoTitle: "बना है",
    svcWhoTitleHL: "लोकल इंडिया के लिए",
    svcCtaTitle: "पहला पोस्टर पाने के लिए तैयार हैं?",
    svcCtaSub: "अभी WhatsApp करें — 30 मिनट में डिलीवरी।",
    svcCtaBtn: "अभी ऑर्डर करें — ₹49",

    // PORTFOLIO PAGE
    portTag: "हमारा पोर्टफोलियो",
    portTitle: "असली बिज़नेस के लिए",
    portTitleHL: "असली पोस्टर",
    portSub: "नीचे हर पोस्टर किसी असली लोकल बिज़नेस के लिए बनाया गया है। स्टाइल चुनें — हम आपके लिए कस्टमाइज़ करेंगे।",
    portPriceNote: "🔥 सभी टेम्पलेट सिर्फ ₹49 में कस्टमाइज़",
    portOrderBtn: "यह पोस्टर ऑर्डर करें",
    portClose: "बंद करें",

    // PRICING PAGE
    priceTag: "पारदर्शी प्राइसिंग",
    priceTitle: "सरल और",
    priceTitleHL: "पारदर्शी प्राइसिंग",
    priceSub: "कोई छुपी फीस नहीं। कोई कॉन्ट्रैक्ट नहीं। जितनी ज़रूरत उतना भुगतान।",
    priceOneTimeTitle: "एक बार के ऑर्डर",
    priceOneTimeSub: "अगर अभी पोस्टर चाहिए तो परफेक्ट",
    priceMonthlyTitle: "मंथली प्लान",
    priceMonthlyBadge: "बेस्ट वैल्यू",
    priceMonthlySub: "उन बिज़नेस के लिए जो नियमित पोस्ट करते हैं",
    priceFaqTitle: "अक्सर पूछे जाने वाले सवाल",
    priceCtaTitle: "अभी भी सोच रहे हैं?",
    priceCtaSub: "पहले ₹49 का फास्ट एडिट आज़माएं — कोई रिस्क नहीं।",
    priceCtaBtn: "₹49 में आज़माएं",
    pricePerMonth: "/महीना",
    pricePostersMonth: "पोस्टर / महीना",
    priceFestival: "फेस्टिवल क्रिएटिव",
    priceSupport: "WhatsApp सपोर्ट",
    pricePriority: "प्रायोरिटी सपोर्ट",
    priceCustom: "कस्टम कैंपेन डिज़ाइन",
    priceMostPopular: "सबसे लोकप्रिय",

    // ORDER PAGE
    orderTag: "फास्ट पोस्टर डिज़ाइन",
    orderTitle: "अपना",
    orderTitleHL: "ऑर्डर शुरू करें",
    orderSub: "ज़्यादातर ऑर्डर 20 मिनट में डिलीवर होते हैं। पहले ड्राफ्ट देखें, पसंद आए तो पेमेंट करें।",
    orderName: "आपका नाम",
    orderNamePH: "जैसे: राहुल शर्मा",
    orderBusiness: "बिज़नेस का नाम",
    orderBusinessPH: "जैसे: शर्मा किराना स्टोर",
    orderType: "सर्विस टाइप",
    orderTypeSub: "फास्ट एडिट (₹49) के लिए पोर्टफोलियो से डिज़ाइन चुनें और हम कस्टमाइज़ करेंगे",
    orderDetails: "पोस्टर की डिटेल्स — जितना बताएंगे, डिज़ाइन उतना बेहतर होगा 😎",
    orderDetailsPH: "पोस्टर में क्या चाहिए? ऑफर, फोन नंबर, पता आदि बताएं।",
    orderBtn: "WhatsApp पर भेजें",
    orderT1: "पहले पेमेंट नहीं",
    orderT2: "पहले ड्राफ्ट, फिर पेमेंट",
    orderT3: "HD फ़ाइल डिलीवरी",

    // CONTACT PAGE
    contactTag: "संपर्क करें",
    contactTitle: "हम यहाँ",
    contactTitleHL: "हैं।",
    contactSub: "कोई सवाल है या कस्टम ऑर्डर देना है? हमसे बात करें — हम जल्दी जवाब देते हैं।",
    contactDetailsTitle: "संपर्क की जानकारी",
    contactDetailsSub: "इनमें से किसी भी माध्यम से संपर्क करें",
    contactHoursTitle: "काम के घंटे",
    contactWACta: "अभी WhatsApp पर चैट करें",
    contactFormTitle: "एक छोटा संदेश भेजें",
    contactFormSub: "यह WhatsApp खोलेगा और आपका संदेश पहले से भरा होगा।",
    contactYourName: "आपका नाम",
    contactYourNamePH: "जैसे: राहुल शर्मा",
    contactEmailPhone: "ईमेल या फोन",
    contactEmailPhonePH: "हम आपसे कैसे संपर्क करें?",
    contactMessage: "संदेश",
    contactMessagePH: "अपना सवाल या रिक्वेस्ट लिखें...",
    contactSendBtn: "WhatsApp पर भेजें",
    contactSentTitle: "संदेश भेज दिया!",
    contactSentSub: "WhatsApp खुल गया होगा। हम जल्द जवाब देंगे!",
    contactSentBtn: "दूसरा संदेश भेजें",
    contactUrgent: "काम के घंटों के बाहर कुछ ज़रूरी है? WhatsApp करें — हम कोशिश करते हैं।",

    // FOOTER
    footerTagline: "भारत के लोकल बिज़नेस के लिए किफायती पोस्टर डिज़ाइन। सिर्फ ₹49 से शुरू।",
    footerPages: "पेज",
    footerContact: "संपर्क",
    footerRights: "सभी अधिकार सुरक्षित।",
    footerMade: "❤️ भारत के लोकल बिज़नेस के लिए बनाया",
  },
};
